micronaut:
  application:
    name: exampleRest

datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""

jpa:
  default:
    entity-scan:
      packages: 'com.github.ankowals.example.rest.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

flyway:
  datasources:
    default:
      enabled: true