micronaut:
  application:
    name: example

datasources:
  default:

jpa:
  default:
    entity-scan:
      packages: 'com.github.ankowals.example.rest.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true