micronaut:
  application:
    name: example

datasources:
  default:
    url:
    username:
    password:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: 'com.github.ankowals.example.rest.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

flyway:
  datasources:
    default:
      enabled: true